/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.cloudrestaurant.panels;

import CloudRestaurant.Conexao;
import br.com.cloudrestaurant.classes.Clientes;
import br.com.cloudrestaurant.classes.Estados;
import br.com.cloudrestaurant.constante.Constantes;
import br.com.cloudrestaurant.utilidades.Metodos;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Debug
 */
public class ClientesPanel extends javax.swing.JPanel {
    
    Clientes clientes;
    Conexao con;
    Connection conn;
    Statement stmt;
    ResultSet rs;
    Constantes constante;
    Estados nomeEstado;
    Metodos metodo = new Metodos();
    
    int idCliente = 0;
    int selecao = 1;
    int estado = 18; // Rio de Janeiro

    /**
     * Creates new form Clientes
     */
    public ClientesPanel() {
        clientes = new Clientes();
        
        initComponents();
        preencheLabels();
        preencheBotoes();
        bloqueiaCampos();
        preencheDatasCidade();
        preencheTabelaClientes(clientes.consultaCliente());
        
    }
    
    public void preencheDatasCidade(){
        
        Date data = new Date(System.currentTimeMillis());
        textDataHoje.setText(String.valueOf(data));
        
        SimpleDateFormat formatado = new SimpleDateFormat("dd/MM/yyyy");
        
        String novaData = formatado.format(data);
        textData.setText(novaData);
        textDataAlteracao.setText(novaData);
        
        textData.setEnabled(false);
        textDataAlteracao.setEnabled(false);
        
        textCidade.setText("Rio de Janeiro");
        textEstado.setText("RJ");
        
        textCidade.setEnabled(false);
        textEstado.setEnabled(false);

        
    }

    public void preencheLabels(){
        labelNome.setText("Nome: ");
        labelDataNascimento.setText("Data Nascimento: ");
        labelEndereco.setText("Endereço: ");
        labelNumero.setText("Número: ");
        labelComplemento.setText("Complemento: ");
        labelBairro.setText("Bairro: ");
        labelCidade.setText("Cidade: ");
        labelEstado.setText("Estado: ");
        labelTelefone.setText("Telefone: ");
        labelCelular.setText("Celular: ");
        labelDataCadastro.setText("Data de cadastro: ");
        labelDataAlteracao.setText("Data de alteração: ");
        labelConsulta.setText("Pesquisa: ");
        radioPorNome.setText("Por Nome");
        radioPorTelefone.setText("Por Telefone");
        labelTipoConsulta.setText("Tipo de Consulta: ");
        labelPedidos.setText("Quantidade de pedidos já feitos: ");
        labelReferencia.setText("Referência: ");
        labelMensagem.setVisible(false);
        textDataHoje.setVisible(false);
        textIdCliente.setVisible(false);
        btPedido.setVisible(false);
    }
    
    public void bloqueiaCampos(){
        textData.setEnabled(false);
        textDataAlteracao.setEnabled(false);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        btIncluir.setEnabled(true);
    }
    public void preencheBotoes(){
        btPedido.setToolTipText("Novo Pedido");
        btIncluir.setToolTipText("Novo Cliente");
        btAlterar.setToolTipText("Alterar Cliente");
        btExcluir.setToolTipText("Excluir Cliente");
        btFechar.setToolTipText("Fechar tela");
        
    }
    public void ocultaIdCliente(){
        textIdCliente.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoes = new javax.swing.ButtonGroup();
        labelTipoConsulta = new javax.swing.JLabel();
        labelConsulta = new javax.swing.JLabel();
        textConsulta = new javax.swing.JTextField();
        radioPorNome = new javax.swing.JRadioButton();
        radioPorTelefone = new javax.swing.JRadioButton();
        panelBotoes = new javax.swing.JPanel();
        btPedido = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        scrollClientes = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        panelDados = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        labelComplemento = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        labelCidade = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelDataNascimento = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelCelular = new javax.swing.JLabel();
        labelDataCadastro = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textEndereco = new javax.swing.JTextField();
        textNumero = new javax.swing.JTextField();
        textComplemento = new javax.swing.JTextField();
        textBairro = new javax.swing.JTextField();
        textCidade = new javax.swing.JTextField();
        textEstado = new javax.swing.JTextField();
        textCelular = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        textData = new javax.swing.JTextField();
        textIdCliente = new javax.swing.JTextField();
        labelPedidos = new javax.swing.JLabel();
        labelQtdePedidos = new javax.swing.JLabel();
        labelMensagem = new javax.swing.JLabel();
        labelDataAlteracao = new javax.swing.JLabel();
        textDataAlteracao = new javax.swing.JTextField();
        textDataHoje = new javax.swing.JTextField();
        labelReferencia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textReferencia = new javax.swing.JTextArea();
        textDataNasc = new javax.swing.JFormattedTextField();

        labelTipoConsulta.setText("jLabel1");

        labelConsulta.setText("jLabel1");

        textConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConsultaActionPerformed(evt);
            }
        });

        grupoBotoes.add(radioPorNome);
        radioPorNome.setSelected(true);
        radioPorNome.setText("jRadioButton1");
        radioPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPorNomeActionPerformed(evt);
            }
        });

        grupoBotoes.add(radioPorTelefone);
        radioPorTelefone.setText("jRadioButton2");
        radioPorTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPorTelefoneActionPerformed(evt);
            }
        });

        panelBotoes.setBackground(new java.awt.Color(153, 153, 255));
        panelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/icone_sac_pedido.png"))); // NOI18N
        btPedido.setText("Venda");
        btPedido.setToolTipText("Nova Venda");
        btPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPedido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btAdicionar.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.setToolTipText("Novo Cliente");
        btIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btAlterarCloud.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setToolTipText("Alterar Cliente");
        btAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btExcluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("Excluir Cliente");
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btSairCloud.png"))); // NOI18N
        btFechar.setText("Sair");
        btFechar.setToolTipText("Sair da tela");
        btFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFechar.setMaximumSize(new java.awt.Dimension(55, 35));
        btFechar.setMinimumSize(new java.awt.Dimension(55, 35));
        btFechar.setPreferredSize(new java.awt.Dimension(55, 35));
        btFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        btCancelar.setBackground(new java.awt.Color(153, 153, 255));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btCancelarCloud.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("Cancelar as Operações");
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setMargin(new java.awt.Insets(2, 7, 2, 7));
        btCancelar.setMaximumSize(new java.awt.Dimension(55, 35));
        btCancelar.setMinimumSize(new java.awt.Dimension(55, 35));
        btCancelar.setPreferredSize(new java.awt.Dimension(55, 35));
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoesLayout.createSequentialGroup()
                        .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addGap(57, 57, 57)
                .addComponent(btPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        scrollClientes.setViewportView(tabelaClientes);

        panelDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNome.setText("jLabel1");

        labelEndereco.setText("jLabel1");

        labelNumero.setText("jLabel1");

        labelComplemento.setText("jLabel1");

        labelBairro.setText("jLabel1");

        labelCidade.setText("jLabel1");

        labelEstado.setText("jLabel1");

        labelDataNascimento.setText("jLabel1");

        labelTelefone.setText("jLabel1");

        labelCelular.setText("jLabel1");

        labelDataCadastro.setText("Data de Cadastro: ");

        textNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumeroKeyTyped(evt);
            }
        });

        textCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCelularKeyTyped(evt);
            }
        });

        textTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTelefoneKeyTyped(evt);
            }
        });

        labelPedidos.setText("Quantidade de pedidos já feitos: ");

        labelQtdePedidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelQtdePedidos.setForeground(new java.awt.Color(0, 0, 204));
        labelQtdePedidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelQtdePedidos.setText("0");

        labelMensagem.setForeground(new java.awt.Color(255, 0, 0));
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMensagem.setText("jLabel1");

        labelDataAlteracao.setText("Data de Alteração: ");

        labelReferencia.setText("jLabel1");

        textReferencia.setColumns(20);
        textReferencia.setRows(5);
        jScrollPane1.setViewportView(textReferencia);

        textDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        textDataNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textDataNascKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addComponent(labelPedidos)
                        .addGap(18, 18, 18)
                        .addComponent(labelQtdePedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(labelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDataCadastro)
                            .addComponent(labelCidade)
                            .addComponent(labelBairro)
                            .addComponent(labelNumero)
                            .addComponent(labelEndereco))
                        .addGap(22, 22, 22)
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelDadosLayout.createSequentialGroup()
                                    .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelComplemento)
                                    .addGap(18, 18, 18)
                                    .addComponent(textComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelDadosLayout.createSequentialGroup()
                                    .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelEstado)
                                    .addGap(29, 29, 29)
                                    .addComponent(textEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1)
                                .addGroup(panelDadosLayout.createSequentialGroup()
                                    .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelDadosLayout.createSequentialGroup()
                                            .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(labelDataAlteracao))
                                        .addComponent(textBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(textEndereco, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelCelular)
                                .addGap(18, 18, 18)
                                .addComponent(textCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDadosLayout.createSequentialGroup()
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome)
                            .addComponent(labelTelefone))
                        .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addGap(480, 480, 480)
                                .addComponent(textIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDadosLayout.createSequentialGroup()
                                .addGap(374, 374, 374)
                                .addComponent(labelDataNascimento)
                                .addGap(18, 18, 18)
                                .addComponent(textDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(labelReferencia))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCelular)
                    .addComponent(textCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNascimento)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome)
                    .addComponent(textDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco)
                    .addComponent(textEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero)
                    .addComponent(labelComplemento)
                    .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBairro)
                    .addComponent(textBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCidade)
                    .addComponent(labelEstado)
                    .addComponent(textCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataCadastro)
                    .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataAlteracao)
                    .addComponent(textDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelReferencia)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPedidos)
                    .addComponent(labelQtdePedidos)
                    .addComponent(labelMensagem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelConsulta)
                        .addGap(37, 37, 37)
                        .addComponent(textConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelTipoConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(radioPorNome)
                        .addGap(10, 10, 10)
                        .addComponent(radioPorTelefone))
                    .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollClientes))
                .addGap(18, 18, 18)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelConsulta)
                            .addComponent(textConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTipoConsulta)
                            .addComponent(radioPorNome)
                            .addComponent(radioPorTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.fechar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btFecharActionPerformed

    public void limpaCampos(){
        metodo.limpaCampos(textTelefone);
        metodo.limpaCampos(textCelular);
        metodo.limpaCampos(textNome);
        metodo.limpaCampos(textEndereco);
        metodo.limpaCampos(textNumero);
        metodo.limpaCampos(textComplemento);
        metodo.limpaCampos(textBairro);
        metodo.limpaCampos(textDataNasc);
        metodo.limpaCamposTextArea(textReferencia);

        bloqueiaCampos();
        preencheDatasCidade();
        textTelefone.requestFocus();
        
    }
    
    public void preencheBarraData(){
        if(textDataNasc.getText().length() == 2){
//        !caracteres.contains(evt.getKeyChar()+""
            textDataNasc.setText(textDataNasc.getText() + "/");
        }
        if(textDataNasc.getText().length() == 5){
            textDataNasc.setText(textDataNasc.getText() + "/");
        }
                   
    }
    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        clientes = new Clientes();
        
        
        textConsulta.setText("");
        limpaCampos();
        btIncluir.setEnabled(true);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        textTelefone.requestFocus();
        preencheTabelaClientes(clientes.consultaCliente());
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarActionPerformed

    private void radioPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPorNomeActionPerformed
        selecao = 1; // consulta por nome
        
// TODO add your handling code here:
    }//GEN-LAST:event_radioPorNomeActionPerformed

    private void radioPorTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPorTelefoneActionPerformed
        selecao = 2; // consulta por telefone        // TODO add your handling code here:
    }//GEN-LAST:event_radioPorTelefoneActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed

        clientes = new Clientes();
        
        
        String dataCadastro = metodo.alteraFormatoDataPadrao(textData.getText());
        String dataAlteracao = metodo.alteraFormatoDataPadrao(textDataAlteracao.getText());
        String dataNascimento = metodo.alteraFormatoDataPadrao(textDataNasc.getText());
        
        if(textDataNasc.getText().equals("")){
            clientes.setDataNascimento(Date.valueOf("1901-01-01"));
        }else{
            clientes.setDataNascimento(Date.valueOf(dataNascimento));
        }

        clientes.setDataCadastro(Date.valueOf(dataCadastro));
        clientes.setDataAlteracao(Date.valueOf(dataAlteracao));
        
        
        clientes.setTelefone(textTelefone.getText());
        clientes.setCelular(textCelular.getText());
        clientes.setNome(textNome.getText());
        clientes.setEndereco(textEndereco.getText());
        if (textNumero.getText().equals("")){
            clientes.setNumero(0);
        }else{
            clientes.setNumero(Integer.parseInt(textNumero.getText()));
        }
        clientes.setComplemento(textComplemento.getText());
        clientes.setBairro(textBairro.getText());
        clientes.setCidade(textCidade.getText());
        clientes.setCodEstado(estado);
        clientes.setReferencia(textReferencia.getText());
        
        clientes.cadastraCliente();
        if (clientes.isCadastro() == true){
            JOptionPane.showMessageDialog(null, constante.SUCCAD, "SUCESSO", constante.SUCESSO);
        }
        limpaCampos();
        preencheTabelaClientes(clientes.consultaCliente());


    }//GEN-LAST:event_btIncluirActionPerformed
    
    private void textNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumeroKeyTyped
        metodo.somenteNumeros(evt);
    }//GEN-LAST:event_textNumeroKeyTyped

    private void textDataNascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDataNascKeyPressed
        preencheBarraData();        // TODO add your handling code here:
    }//GEN-LAST:event_textDataNascKeyPressed

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        int linhaSelecionada = tabelaClientes.getSelectedRow();
        
        btIncluir.setEnabled(false);
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
        
        buscaClientes(tabelaClientes.getValueAt(linhaSelecionada, 0).toString());
        
    }//GEN-LAST:event_tabelaClientesMouseClicked

   
    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed

        constante = new Constantes();
        
        if (JOptionPane.showConfirmDialog(null, constante.ALTERACAO, "ATENÇÃO", JOptionPane.YES_NO_OPTION) == 0){

        String dataCadastro = metodo.alteraFormatoDataPadrao(textData.getText());
//        String dataAlteracao = con.alteraFormatoDataPadrao(textDataHoje.getText());
        String dataNascimento = metodo.alteraFormatoDataPadrao(textDataNasc.getText());
        
            clientes = new Clientes();
            
            clientes.setIdCliente(Integer.parseInt(textIdCliente.getText()));
            clientes.setTelefone(textTelefone.getText());
            clientes.setCelular(textCelular.getText());
            clientes.setNome(textNome.getText());
            clientes.setEndereco(textEndereco.getText());
            clientes.setNumero(Integer.parseInt(textNumero.getText()));
            clientes.setComplemento(textComplemento.getText());
            clientes.setBairro(textBairro.getText());
            clientes.setCidade(textCidade.getText());
            clientes.setCodEstado(estado);
            clientes.setReferencia(textReferencia.getText());
            clientes.setDataCadastro(Date.valueOf(dataCadastro));
            clientes.setDataAlteracao(Date.valueOf(textDataHoje.getText()));
            clientes.setDataNascimento(Date.valueOf(dataNascimento));
            
            clientes.alteraCliente();
            limpaCampos();
            preencheTabelaClientes(clientes.consultaCliente());
        
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        clientes = new Clientes();
        constante = new Constantes();
        
        clientes.setIdCliente(Integer.parseInt(textIdCliente.getText()));
        
        clientes.excluiCliente();
        limpaCampos();
        preencheTabelaClientes(clientes.consultaCliente());
        
// TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void textConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConsultaActionPerformed
        clientes = new Clientes();
        
            String sql = clientes.consultaCliente();

            if (selecao == 1){
                sql = sql + " WHERE nome LIKE '%" + textConsulta.getText() + "%'"; 
                preencheTabelaClientes(sql);
            }else if(selecao == 2){
                sql = sql + " WHERE telefone LIKE '%" + textConsulta.getText() + "%'";
                preencheTabelaClientes(sql);
            }else{
                preencheTabelaClientes(sql);
            }
           
        
// TODO add your handling code here:
    }//GEN-LAST:event_textConsultaActionPerformed

    private void textTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelefoneKeyTyped
        metodo = new Metodos();
        
        metodo.somenteNumeros(evt);
        
// TODO add your handling code here:
    }//GEN-LAST:event_textTelefoneKeyTyped

    private void textCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCelularKeyTyped
        metodo = new Metodos();
        metodo.somenteNumeros(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_textCelularKeyTyped
    
    public void buscaClientes(String buscaCliente){
        clientes = new Clientes();
        constante = new Constantes();
        
        try{
        String sql = clientes.consultaCliente() + " "
                + "WHERE nome = '" + buscaCliente + "' OR "
                + "telefone = '" + buscaCliente + "'";
        
        con = new Conexao();
        Connection conn = con.getConnection();
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();
        
        if (rs.absolute(1)){
            textIdCliente.setText(String.valueOf(rs.getInt("idCliente")));
            textTelefone.setText(rs.getString("telefone"));
            textCelular.setText(rs.getString("celular"));
            textNome.setText(rs.getString("nome"));
            textEndereco.setText(rs.getString("endereco"));
            textNumero.setText(String.valueOf(rs.getInt("numero")));
            textComplemento.setText(rs.getString("complemento"));
            textBairro.setText(rs.getString("bairro"));
            textCidade.setText(rs.getString("cidade"));
            textEstado.setText(buscaEstado(rs.getInt("codEstado")));
            textData.setText(rs.getString("dataCadFormat"));
            textDataAlteracao.setText(rs.getString("dataAlterFormat"));
            textDataNasc.setText(rs.getString("dataNascFormat"));
            textReferencia.setText(rs.getString("referencia"));
        }else{
            labelMensagem.setVisible(true);
            labelMensagem.setText("Não contém clientes.");
        }
        
        
        }catch(IOException | SQLException ex){
            JOptionPane.showMessageDialog(null, constante.ERROCONS + "Erro:" + ex, "ERRO", constante.ERROR);
        }
     
        
    }
    
    public String buscaEstado(int estado){
        nomeEstado = new Estados();
        
        return nomeEstado.retornaEstado(estado);
        
    }
    
    public void fechar(){
        this.setVisible(false);
    }

    public void preencheTabelaClientes(String sql){
        ArrayList dados = new ArrayList();
        String[] nomeColunas = new String[]{"TELEFONE","NOME","DATA NASCIMENTO"};
        
        try{
            con = new Conexao();
            Connection conn = con.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            rs.first();
            
            do{
                dados.add(new Object[]{rs.getString("telefone"), rs.getString("nome"), rs.getString("dataNascFormat")});
            }while(rs.next());
            
        ModeloTabela modelo = new ModeloTabela(dados, nomeColunas);
        tabelaClientes.setModel(modelo);
        tabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(100); // define o tamanho da coluna.
        tabelaClientes.getColumnModel().getColumn(0).setResizable(false);// Não poderá alterar o tamanho.
        tabelaClientes.getColumnModel().getColumn(1).setPreferredWidth(300); // define o tamanho da coluna.
        tabelaClientes.getColumnModel().getColumn(1).setResizable(false);// Não poderá alterar o tamanho.
        tabelaClientes.getColumnModel().getColumn(2).setPreferredWidth(150); // define o tamanho da coluna.
        tabelaClientes.getColumnModel().getColumn(2).setResizable(false);// Não poderá alterar o tamanho.
        
        tabelaClientes.getTableHeader().setReorderingAllowed(false);
        tabelaClientes.setAutoResizeMode(tabelaClientes.AUTO_RESIZE_OFF);
        
        tabelaClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
        }catch(IOException | SQLException ex){
            //JOptionPane.showMessageDialog(null, "Problmeas. Erro: " + ex.getMessage());
            labelMensagem.setVisible(true);
            labelMensagem.setText("Não há registro na tabela. Inclua um novo.");
        }
        
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btPedido;
    private javax.swing.ButtonGroup grupoBotoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelComplemento;
    private javax.swing.JLabel labelConsulta;
    private javax.swing.JLabel labelDataAlteracao;
    private javax.swing.JLabel labelDataCadastro;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelPedidos;
    private javax.swing.JLabel labelQtdePedidos;
    private javax.swing.JLabel labelReferencia;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTipoConsulta;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelDados;
    private javax.swing.JRadioButton radioPorNome;
    private javax.swing.JRadioButton radioPorTelefone;
    private javax.swing.JScrollPane scrollClientes;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTextField textBairro;
    private javax.swing.JTextField textCelular;
    private javax.swing.JTextField textCidade;
    private javax.swing.JTextField textComplemento;
    private javax.swing.JTextField textConsulta;
    private javax.swing.JTextField textData;
    private javax.swing.JTextField textDataAlteracao;
    private javax.swing.JTextField textDataHoje;
    private javax.swing.JFormattedTextField textDataNasc;
    private javax.swing.JTextField textEndereco;
    private javax.swing.JTextField textEstado;
    private javax.swing.JTextField textIdCliente;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextArea textReferencia;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
