/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.cloudrestaurant.panels;

import br.com.cloudrestaurant.classes.Estados;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import CloudRestaurant.Conexao;


/**
 *
 * @author Debug
 */
public final class EstadosPanel extends javax.swing.JPanel {
    
    private int selecao = 1;

    /**
     * Creates new form Estados
     */
    public EstadosPanel() {
        initComponents();
        ocultaMensagens();
        preencheLabelsRadios();
        preencheBotao();
        preencheTabelaEstados("SELECT * FROM estados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruppoBotoes = new javax.swing.ButtonGroup();
        panelEstados = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCadastro = new javax.swing.JPanel();
        labelNomeEstado = new javax.swing.JLabel();
        labelSigla = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        txtNomeEstado = new javax.swing.JTextField();
        btEnviar = new javax.swing.JButton();
        labelMensagemCad = new javax.swing.JLabel();
        labelImageEstado = new javax.swing.JLabel();
        labelImageSigla = new javax.swing.JLabel();
        panelAlterExclusao = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEstados = new javax.swing.JTable();
        labelEstado = new javax.swing.JLabel();
        labelSiglaPesquisa = new javax.swing.JLabel();
        textBuscaNome = new javax.swing.JTextField();
        textBuscaSigla = new javax.swing.JTextField();
        btAlterar = new javax.swing.JButton();
        labelCampoPesquisa = new javax.swing.JLabel();
        textLocaliza = new javax.swing.JTextField();
        radioNome = new javax.swing.JRadioButton();
        radioSigla = new javax.swing.JRadioButton();
        labelTipoConsulta = new javax.swing.JLabel();
        labelMensagemOutros = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        textId = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btLimpar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        panelEstados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEstados.setPreferredSize(new java.awt.Dimension(500, 514));

        jTabbedPane1.setName(""); // NOI18N

        labelNomeEstado.setText("Nome Estado:");

        labelSigla.setText("Sigla:");

        txtSigla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSiglaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSiglaKeyTyped(evt);
            }
        });

        txtNomeEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeEstadoKeyPressed(evt);
            }
        });

        btEnviar.setText("Cadastrar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        labelMensagemCad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMensagemCad.setForeground(new java.awt.Color(255, 51, 51));
        labelMensagemCad.setText("jLabel1");

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelMensagemCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomeEstado)
                            .addComponent(labelSigla))
                        .addGap(18, 18, 18)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEnviar)
                            .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImageEstado)
                    .addComponent(labelImageSigla))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeEstado)
                    .addComponent(txtNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImageEstado))
                .addGap(18, 18, 18)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSigla)
                    .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImageSigla))
                .addGap(35, 35, 35)
                .addComponent(btEnviar)
                .addGap(45, 45, 45)
                .addComponent(labelMensagemCad)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro                      ", panelCadastro);

        tabelaEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEstadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaEstados);

        labelEstado.setText("jLabel1");

        labelSiglaPesquisa.setText("jLabel2");

        textBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscaNomeActionPerformed(evt);
            }
        });

        textBuscaSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscaSiglaActionPerformed(evt);
            }
        });

        btAlterar.setMaximumSize(new java.awt.Dimension(55, 35));
        btAlterar.setMinimumSize(new java.awt.Dimension(55, 35));
        btAlterar.setPreferredSize(new java.awt.Dimension(55, 35));
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        labelCampoPesquisa.setText("jLabel5");

        textLocaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLocalizaActionPerformed(evt);
            }
        });

        gruppoBotoes.add(radioNome);
        radioNome.setSelected(true);
        radioNome.setText("jRadioButton1");
        radioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNomeActionPerformed(evt);
            }
        });

        gruppoBotoes.add(radioSigla);
        radioSigla.setText("jRadioButton2");
        radioSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiglaActionPerformed(evt);
            }
        });

        labelTipoConsulta.setText("jLabel3");

        labelMensagemOutros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMensagemOutros.setForeground(new java.awt.Color(255, 0, 0));
        labelMensagemOutros.setText("jLabel1");

        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlterExclusaoLayout = new javax.swing.GroupLayout(panelAlterExclusao);
        panelAlterExclusao.setLayout(panelAlterExclusaoLayout);
        panelAlterExclusaoLayout.setHorizontalGroup(
            panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlterExclusaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlterExclusaoLayout.createSequentialGroup()
                        .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                            .addGroup(panelAlterExclusaoLayout.createSequentialGroup()
                                .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAlterExclusaoLayout.createSequentialGroup()
                                        .addComponent(labelTipoConsulta)
                                        .addGap(109, 109, 109)
                                        .addComponent(radioNome)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioSigla))
                                    .addComponent(labelMensagemOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelAlterExclusaoLayout.createSequentialGroup()
                                        .addComponent(labelCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(textLocaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlterExclusaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSiglaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBuscaSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(panelAlterExclusaoLayout.createSequentialGroup()
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir))))
        );
        panelAlterExclusaoLayout.setVerticalGroup(
            panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlterExclusaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNome)
                    .addComponent(radioSigla)
                    .addComponent(labelTipoConsulta))
                .addGap(16, 16, 16)
                .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCampoPesquisa)
                    .addComponent(textLocaliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstado)
                    .addComponent(textBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBuscaSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSiglaPesquisa))
                .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlterExclusaoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelAlterExclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExcluir)))
                    .addGroup(panelAlterExclusaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(labelMensagemOutros)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta / Alteração / Exclusão", panelAlterExclusao);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btLimpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFechar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btLimpar)
                .addGap(11, 11, 11)
                .addComponent(btFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelEstadosLayout = new javax.swing.GroupLayout(panelEstados);
        panelEstados.setLayout(panelEstadosLayout);
        panelEstadosLayout.setHorizontalGroup(
            panelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelEstadosLayout.setVerticalGroup(
            panelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelEstadosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        
        if ((txtNomeEstado.getText().equals("")) || (txtSigla.getText().equals(""))){
        
            labelMensagemCad.setVisible(true);
            labelMensagemCad.setText("Não é permitido campo(s) vazio(s).");
            this.txtNomeEstado.requestFocus();
            
        }else{
        
        Estados estado = new Estados();
        
        estado.setNome(txtNomeEstado.getText());
        estado.setSigla(txtSigla.getText());
        
        estado.cadastraEstado();
        labelMensagemCad.setVisible(true);
        labelMensagemCad.setText("Estados inserido com sucesso!");
        preencheTabelaEstados("SELECT * FROM estados");
        
        this.txtNomeEstado.setText("");
        this.txtSigla.setText("");
        this.txtNomeEstado.requestFocus();
        
        
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btEnviarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
//        this.setVisible(false);
        textLocaliza.setText("");
        
    }//GEN-LAST:event_btLimparActionPerformed

    public void preencheLabelsRadios(){
        labelTipoConsulta.setText("Tipo de consulta: ");
        radioNome.setText("por Estado");
        radioSigla.setText("por Sigla");
        labelCampoPesquisa.setText("Campo de pesquisa: ");
        labelEstado.setText("Estado: ");
        labelSiglaPesquisa.setText("Sigla: ");
    }
    
    public void preencheBotao(){
        btFechar.setText("Fechar");
        btLimpar.setText("Limpar");
    }
    
    public void ocultaMensagens(){
        labelMensagemCad.setVisible(false);
        labelMensagemOutros.setVisible(false);
        labelImageEstado.setVisible(false);
        labelImageSigla.setVisible(false);
        textId.setVisible(false);
    }
    
    private void txtSiglaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSiglaKeyTyped

    int k = evt.getKeyChar();  
    if (txtSigla.getText().length() <= 2 - 1) {  
                     //deixe passar  
    } else {  
        evt.setKeyChar((char) evt.VK_CLEAR);  
    } 
// TODO add your handling code here:
    }//GEN-LAST:event_txtSiglaKeyTyped

    private void textBuscaSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscaSiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscaSiglaActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed

        this.fechar();

// TODO add your handling code here:
    }//GEN-LAST:event_btFecharActionPerformed

    private void radioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNomeActionPerformed
        selecao = 1; // Informa tipo de consulta por nome
        
// TODO add your handling code here:
    }//GEN-LAST:event_radioNomeActionPerformed

    private void radioSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiglaActionPerformed
        selecao = 2;
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSiglaActionPerformed

    private void textLocalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLocalizaActionPerformed
        if (selecao == 1){
            preencheTabelaEstados("SELECT * FROM estados WHERE estado='" + textLocaliza.getText() + "'");
            
        }else if (selecao == 2){
            preencheTabelaEstados("SELECT * FROM estados WHERE sigla='" + textLocaliza.getText() + "'");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_textLocalizaActionPerformed

    private void tabelaEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEstadosMouseClicked
        int linhaSelecionada = tabelaEstados.getSelectedRow();
        
        textId.setText(tabelaEstados.getValueAt(linhaSelecionada, 0).toString());
        textBuscaNome.setText(tabelaEstados.getValueAt(linhaSelecionada, 1).toString());
        textBuscaSigla.setText(tabelaEstados.getValueAt(linhaSelecionada, 2).toString());
        
    }//GEN-LAST:event_tabelaEstadosMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        Estados estado = new Estados();
        
        int codigo = Integer.parseInt(textId.getText());
        
        estado.setIdEstado(codigo);
        
        estado.excluiEstado();
        
        labelMensagemOutros.setVisible(true);
        labelMensagemOutros.setText("Estado excluído com sucesso!");
        preencheTabelaEstados("SELECT * FROM estados");
        

// TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void txtNomeEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeEstadoKeyPressed
        ImageIcon sucesso = new ImageIcon("C:\\Users\\Debug\\Documents\\NetBeansProjects\\Satoru\\images\\IconeCheckC.png");
        ImageIcon erro = new ImageIcon("C:\\Users\\Debug\\Documents\\NetBeansProjects\\Satoru\\images\\excluir1.png");
        
        if (txtNomeEstado.getText() != ""){
            labelImageEstado.setVisible(true);
            labelImageEstado.setIcon(sucesso);
        }else{
            labelImageEstado.setVisible(true);
            labelImageEstado.setIcon(erro);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEstadoKeyPressed

    private void txtSiglaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSiglaKeyPressed
        ImageIcon sucesso = new ImageIcon("C:\\Users\\Debug\\Documents\\NetBeansProjects\\Satoru\\images\\IconeCheckC.png");
        ImageIcon erro = new ImageIcon("C:\\Users\\Debug\\Documents\\NetBeansProjects\\Satoru\\images\\excluir1.png");
        
        if (txtSigla.getText() != ""){
            labelImageSigla.setVisible(true);
            labelImageSigla.setIcon(sucesso);
        }else{
            labelImageSigla.setVisible(true);
            labelImageSigla.setIcon(erro);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiglaKeyPressed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        Estados estado = new Estados();
        
        if (textBuscaNome.getText().isEmpty() == false  || textBuscaSigla.getText().isEmpty() == false){
            int codigo = Integer.parseInt(textId.getText());
            
            estado.setIdEstado(codigo);
            estado.setNome(textBuscaNome.getText());
            estado.setSigla(textBuscaSigla.getText());
            
            estado.alteraEstado();
            
            labelMensagemOutros.setVisible(true);
            labelMensagemOutros.setText("Estado alterado com sucesso!");
            preencheTabelaEstados("SELECT * FROM estados");

            
        }else{
            labelMensagemOutros.setVisible(true);
            labelMensagemOutros.setText("Não é permitido campos vazios!");
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btAlterarActionPerformed

    private void textBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscaNomeActionPerformed

    public void fechar(){
        this.setVisible(false);
    }
    
    public void preencheTabelaEstados(String sql){

        ArrayList dados = new ArrayList();
        String[] nomeColunas = new String[]{"CÓDIGO","NOME","SIGLA"};

        try{
        Conexao con = new Conexao();
        Connection conn = con.getConnection();
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
            rs.first();
            do{
                dados.add(new Object[]{rs.getInt("idEstado"), rs.getString("estado"), rs.getString("sigla")});
//                dados.add(new Object[]{rs.getInt("idEstado"), rs.getString("estado"), rs.getString("sigla")});
            }
            while (rs.next());
        }catch(IOException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Não foi possível consultar o banco de dados. Erro: " + ex.getMessage(), "ATENÇÃO", 0);
        }
        //Aqui monta a estrutura da tabela.
        ModeloTabela modelo = new ModeloTabela(dados, nomeColunas);
        tabelaEstados.setModel(modelo);
        tabelaEstados.getColumnModel().getColumn(0).setPreferredWidth(80); // define o tamanho da coluna.
        tabelaEstados.getColumnModel().getColumn(0).setResizable(false);// Não poderá alterar o tamanho.
        tabelaEstados.getColumnModel().getColumn(1).setPreferredWidth(180); // define o tamanho da coluna.
        tabelaEstados.getColumnModel().getColumn(1).setResizable(false);// Não poderá alterar o tamanho.
        tabelaEstados.getColumnModel().getColumn(2).setPreferredWidth(80); // define o tamanho da coluna.
        tabelaEstados.getColumnModel().getColumn(2).setResizable(false);// Não poderá alterar o tamanho.
        
        tabelaEstados.getTableHeader().setReorderingAllowed(false);
        tabelaEstados.setAutoResizeMode(tabelaEstados.AUTO_RESIZE_OFF);
        
        tabelaEstados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup gruppoBotoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCampoPesquisa;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelImageEstado;
    private javax.swing.JLabel labelImageSigla;
    private javax.swing.JLabel labelMensagemCad;
    private javax.swing.JLabel labelMensagemOutros;
    private javax.swing.JLabel labelNomeEstado;
    private javax.swing.JLabel labelSigla;
    private javax.swing.JLabel labelSiglaPesquisa;
    private javax.swing.JLabel labelTipoConsulta;
    private javax.swing.JPanel panelAlterExclusao;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JPanel panelEstados;
    private javax.swing.JRadioButton radioNome;
    private javax.swing.JRadioButton radioSigla;
    private javax.swing.JTable tabelaEstados;
    private javax.swing.JTextField textBuscaNome;
    private javax.swing.JTextField textBuscaSigla;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textLocaliza;
    private javax.swing.JTextField txtNomeEstado;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
