/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.cloudrestaurant.panels;

import br.com.cloudrestaurant.classes.Frete;
import br.com.cloudrestaurant.classes.TipoVenda;
import br.com.cloudrestaurant.constante.Constantes;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import CloudRestaurant.Conexao;

/**
 *
 * @author Debug
 */
public class FretePanel extends javax.swing.JPanel {
    
    Frete frete = new Frete();

    /**
     * Creates new form FretePanel
     */
    public FretePanel() {
        initComponents();
        preencheLabels();
        preencheBotoes();
        desativaBotoes();
        preencheTabelaFrete(frete.consultaFrete());
        textIdFrete.setVisible(false);
    }
    
    public void desativaBotoes(){
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
    }
    
    Constantes constante = new Constantes();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        panelBotao = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        labelPesquisa = new javax.swing.JLabel();
        textPesquisa = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFrete = new javax.swing.JTable();
        textIdFrete = new javax.swing.JTextField();

        panelCentral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelBotao.setBackground(new java.awt.Color(153, 153, 255));

        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btAdicionar.png"))); // NOI18N
        btCadastrar.setToolTipText("");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btAlterarCloud.png"))); // NOI18N
        btAlterar.setToolTipText("");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btExcluir.png"))); // NOI18N
        btExcluir.setToolTipText("");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btSairCloud.png"))); // NOI18N
        btFechar.setToolTipText("Fechar");
        btFechar.setMaximumSize(new java.awt.Dimension(55, 35));
        btFechar.setMinimumSize(new java.awt.Dimension(55, 35));
        btFechar.setPreferredSize(new java.awt.Dimension(55, 35));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        btCancelar.setBackground(new java.awt.Color(153, 153, 255));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btCancelarCloud.png"))); // NOI18N
        btCancelar.setToolTipText("Cancelar");
        btCancelar.setMaximumSize(new java.awt.Dimension(55, 35));
        btCancelar.setMinimumSize(new java.awt.Dimension(55, 35));
        btCancelar.setPreferredSize(new java.awt.Dimension(55, 35));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotaoLayout = new javax.swing.GroupLayout(panelBotao);
        panelBotao.setLayout(panelBotaoLayout);
        panelBotaoLayout.setHorizontalGroup(
            panelBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotaoLayout.setVerticalGroup(
            panelBotaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addGap(18, 18, 18)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelPesquisa.setText("jLabel1");

        textPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPesquisaActionPerformed(evt);
            }
        });

        labelNome.setText("jLabel2");

        tabelaFrete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaFrete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFreteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFrete);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome)
                            .addComponent(labelPesquisa))
                        .addGap(31, 31, 31)
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textIdFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(panelBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addComponent(panelBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPesquisa))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(textIdFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        fechar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btFecharActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
       
        frete.setNome(textNome.getText());
        frete.cadastraFrete();
        textNome.setText("");
        textNome.requestFocus();
        preencheTabelaFrete(frete.consultaFrete());
        
// TODO add your handling code here:
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void tabelaFreteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFreteMouseClicked

        int linhaSelecionada = tabelaFrete.getSelectedRow();
        
        this.btCadastrar.setEnabled(false);
        this.btAlterar.setEnabled(true);
        this.btExcluir.setEnabled(true);
        
        textIdFrete.setText(tabelaFrete.getValueAt(linhaSelecionada, 0).toString());
        textNome.setText(tabelaFrete.getValueAt(linhaSelecionada, 1).toString());
        
// TODO add your handling code here:
    }//GEN-LAST:event_tabelaFreteMouseClicked

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if (consultaCampos() != null){

            frete.setIdFrete(Integer.parseInt(textIdFrete.getText()));
            frete.setNome(textNome.getText());
            frete.alteraFrete();
            textNome.setText("");
            textNome.requestFocus();
            desativaBotoes();
            btCadastrar.setEnabled(true);
            preencheTabelaFrete(frete.consultaFrete());
        }else{
            textNome.requestFocus();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btAlterarActionPerformed

    private void textPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPesquisaActionPerformed
        if (textPesquisa.getText().equals("")){

            preencheTabelaFrete(frete.consultaFrete());
        }else{
            preencheTabelaFrete(frete.consultaFrete() + " WHERE nome = '" + textPesquisa.getText() + "'");
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_textPesquisaActionPerformed

    public String consultaCampos(){
        if (textIdFrete.getText().equals("") || textNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Não é permitido campo vazio para esta operação.", "ERRO", constante.ERROR);
            return null;
        }
        return "Não é vazio.";
    }
    
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (consultaCampos() != null){

            frete.setIdFrete(Integer.parseInt(textIdFrete.getText()));
            frete.excluiFrete();
            textNome.setText("");
            textNome.requestFocus();
            desativaBotoes();
            btCadastrar.setEnabled(true);
            
            preencheTabelaFrete(frete.consultaFrete());
        }else{
            textNome.requestFocus();
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed

        textPesquisa.setText("");
        textNome.setText("");
        btCadastrar.setEnabled(true);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
        textNome.requestFocus();
        preencheTabelaFrete(frete.consultaFrete());
// TODO add your handling code here:
    }//GEN-LAST:event_btCancelarActionPerformed

    public void fechar(){
//        JOptionPane.showMessageDialog(null, "TESTE1", "TESTE2", 0);
        this.setVisible(false);
    }
    
    public void preencheLabels(){
        labelNome.setText("Frete: ");
        labelPesquisa.setText("Pesquisa: ");
    }
    
    public void preencheBotoes(){
        btAlterar.setToolTipText("Alterar");
        btExcluir.setToolTipText("Excluir");
        btCadastrar.setToolTipText("Incluir");
        btFechar.setToolTipText("Sair do Painel");
    }
    
    public void preencheTabelaFrete(String sql){
        ArrayList dados = new ArrayList();
        String[] nomeColunas = new String[]{"CÓDIGO","FRETE"};
        
        try{
            Conexao con = new Conexao();
            Connection conn = con.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            rs.first();
            do{
                dados.add(new Object[]{rs.getInt("idFrete"), rs.getString("nome")});
            }while(rs.next());
            
        ModeloTabela modelo = new ModeloTabela(dados, nomeColunas);
        tabelaFrete.setModel(modelo);
        tabelaFrete.getColumnModel().getColumn(0).setPreferredWidth(80); // define o tamanho da coluna.
        tabelaFrete.getColumnModel().getColumn(0).setResizable(false);// Não poderá alterar o tamanho.
        tabelaFrete.getColumnModel().getColumn(1).setPreferredWidth(180); // define o tamanho da coluna.
        tabelaFrete.getColumnModel().getColumn(1).setResizable(false);// Não poderá alterar o tamanho.
        
        tabelaFrete.getTableHeader().setReorderingAllowed(false);
        tabelaFrete.setAutoResizeMode(tabelaFrete.AUTO_RESIZE_OFF);
        
        tabelaFrete.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
        }catch(IOException | SQLException ex){
                JOptionPane.showMessageDialog(null, "Não há registro na tabela. Inclua um novo!", "Registro vazio", 0);

//            JOptionPane.showMessageDialog(this, "Não foi possível preencher a tabela. Erro: " + ex.getMessage(), "ERRO", 0);
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPesquisa;
    private javax.swing.JPanel panelBotao;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JTable tabelaFrete;
    private javax.swing.JTextField textIdFrete;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textPesquisa;
    // End of variables declaration//GEN-END:variables
}
