/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.cloudrestaurant.panels;

import CloudRestaurant.Conexao;
import br.com.cloudrestaurant.classes.Fornecedores;
import br.com.cloudrestaurant.classes.Itens;
import br.com.cloudrestaurant.utilidades.Metodos;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Debug
 */
public class ItensPanel extends javax.swing.JPanel {
    
    Metodos metodo;
    Conexao con;
    Connection conn;
    Statement stmt;
    ResultSet rs;
    Itens item;

    /**
     * Creates new form Produtos
     */
    public ItensPanel() {
        initComponents();
        item = new Itens();
        ocultaCombo();
        preencheLabels();
        bloqueiaBotoes();
        preencheTabelaItens(item.consultaItem());
        preencheComboFornecedor();
        preencheDataHora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotoes = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        labelBusca = new javax.swing.JLabel();
        textBusca = new javax.swing.JTextField();
        panelItens = new javax.swing.JPanel();
        labelItem = new javax.swing.JLabel();
        textItem = new javax.swing.JTextField();
        textIdFornecedor = new javax.swing.JTextField();
        labelFornecedor = new javax.swing.JLabel();
        textFornecedor = new javax.swing.JTextField();
        btSelectFornecedor = new javax.swing.JButton();
        comboFornecedor = new javax.swing.JComboBox();
        labelValorCusto = new javax.swing.JLabel();
        textValorCusto = new javax.swing.JTextField();
        labelValorVenda = new javax.swing.JLabel();
        textValorVenda = new javax.swing.JTextField();
        labelQuantidade = new javax.swing.JLabel();
        textQuantidade = new javax.swing.JTextField();
        labelDesconto = new javax.swing.JLabel();
        textDesconto = new javax.swing.JTextField();
        textAcrescimo = new javax.swing.JTextField();
        labelAcrescimo = new javax.swing.JLabel();
        textIdItem = new javax.swing.JTextField();
        textDataHoje = new javax.swing.JTextField();
        labelMensagem = new javax.swing.JLabel();

        panelBotoes.setBackground(new java.awt.Color(153, 153, 255));
        panelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btAdicionar.png"))); // NOI18N
        btIncluir.setText("Inserir");
        btIncluir.setToolTipText("Inserir o Item");
        btIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btAlterarCloud.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setToolTipText("Alterar o Item");
        btAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btExcluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("Excluir o Item");
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btSairCloud.png"))); // NOI18N
        btFechar.setText("Sair");
        btFechar.setToolTipText("Sair da tela");
        btFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFechar.setMaximumSize(new java.awt.Dimension(55, 35));
        btFechar.setMinimumSize(new java.awt.Dimension(55, 35));
        btFechar.setPreferredSize(new java.awt.Dimension(55, 35));
        btFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btCancelarCloud.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("Cancelar as operações");
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setMargin(new java.awt.Insets(2, 7, 2, 7));
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btIncluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFechar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaItensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaItens);

        labelBusca.setText("Busca:");

        textBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscaActionPerformed(evt);
            }
        });

        panelItens.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelItem.setText("Nome do Item:");

        labelFornecedor.setText("Fornecedor: ");

        btSelectFornecedor.setText("...");
        btSelectFornecedor.setToolTipText("Seleciona o fornecedor");
        btSelectFornecedor.setMaximumSize(new java.awt.Dimension(45, 20));
        btSelectFornecedor.setMinimumSize(new java.awt.Dimension(45, 20));
        btSelectFornecedor.setPreferredSize(new java.awt.Dimension(45, 20));
        btSelectFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectFornecedorActionPerformed(evt);
            }
        });

        comboFornecedor.setMaximumSize(new java.awt.Dimension(28, 20));
        comboFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFornecedorActionPerformed(evt);
            }
        });

        labelValorCusto.setText("Valor Custo: ");

        textValorCusto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValorCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textValorCustoKeyTyped(evt);
            }
        });

        labelValorVenda.setText("Valor Venda: ");

        textValorVenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textValorVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textValorVendaKeyTyped(evt);
            }
        });

        labelQuantidade.setText("Quantidade: ");

        textQuantidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textQuantidadeKeyTyped(evt);
            }
        });

        labelDesconto.setText("Desconto: ");

        textDesconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDescontoKeyTyped(evt);
            }
        });

        textAcrescimo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textAcrescimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAcrescimoKeyTyped(evt);
            }
        });

        labelAcrescimo.setText("Acréscimo: ");

        javax.swing.GroupLayout panelItensLayout = new javax.swing.GroupLayout(panelItens);
        panelItens.setLayout(panelItensLayout);
        panelItensLayout.setHorizontalGroup(
            panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelItem)
                    .addComponent(labelQuantidade)
                    .addComponent(labelValorCusto)
                    .addComponent(labelDesconto)
                    .addComponent(labelFornecedor))
                .addGap(18, 18, 18)
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelItensLayout.createSequentialGroup()
                        .addComponent(textDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(labelAcrescimo)
                        .addGap(19, 19, 19)
                        .addComponent(textAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelItensLayout.createSequentialGroup()
                        .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(textIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelItensLayout.createSequentialGroup()
                        .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelItensLayout.createSequentialGroup()
                                .addComponent(labelValorVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelItensLayout.createSequentialGroup()
                                .addComponent(btSelectFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(textItem, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelItensLayout.setVerticalGroup(
            panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelectFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorCusto)
                    .addComponent(textValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorVenda)
                    .addComponent(textValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidade)
                    .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDataHoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesconto)
                    .addComponent(labelAcrescimo)
                    .addComponent(textDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelMensagem.setForeground(new java.awt.Color(255, 0, 0));
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMensagem.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelBusca)
                        .addGap(30, 30, 30)
                        .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(panelItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBusca)
                            .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMensagem))
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.fechar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btFecharActionPerformed

    private void btSelectFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectFornecedorActionPerformed
        comboFornecedor.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btSelectFornecedorActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed

        item = new Itens();
        
        item.setNome(textItem.getText());

        try {
            Double valorCusto = NumberFormat.getInstance().parse(textValorCusto.getText()).doubleValue();
            Double valorVenda = NumberFormat.getInstance().parse(textValorVenda.getText()).doubleValue();
            Double valorDesconto = NumberFormat.getInstance().parse(textDesconto.getText()).doubleValue();
            Double valorAcrescimo = NumberFormat.getInstance().parse(textAcrescimo.getText()).doubleValue();
            
            
            item.setValorCusto(valorCusto);
            item.setValorVenda(valorVenda);
            item.setDesconto(valorDesconto);
            item.setAcrescimo(valorAcrescimo);
        } catch (ParseException ex) {
            Logger.getLogger(ItensPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        item.setQuantidade(Integer.parseInt(textQuantidade.getText()));
        item.setMensagem(Boolean.TRUE);
        
        if(textIdFornecedor.getText().equals("")){
            Fornecedores fornecedor = new Fornecedores();
            
            fornecedor.setNome(textFornecedor.getText());
            fornecedor.setDataCadastro(Date.valueOf(textDataHoje.getText()));
            fornecedor.setDataAlteracao(Date.valueOf(textDataHoje.getText()));
            fornecedor.setCodEstado(18);//Código estado do Rio de Janeiro
            fornecedor.setMensagem(false); //Não precisa informar a mensagem de sucesso ou erro.
            
            item.setCodFornecedor(fornecedor.consultaUltimoId());
            
            fornecedor.cadastraFornecedor();
            
            
            
        }else{
            item.setCodFornecedor(Integer.parseInt(textIdFornecedor.getText()));
        }
        
        item.cadastraItem();
        limpaDados();
        preencheComboFornecedor();
        preencheTabelaItens(item.consultaItem());
        
// TODO add your handling code here:
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        item = new Itens();
        
        item.setIdItens(Integer.valueOf(textIdItem.getText()));
        item.setNome(textItem.getText());
        item.setValorCusto(Double.parseDouble(textValorCusto.getText()));

        try {
            Double valorCusto = NumberFormat.getInstance().parse(textValorCusto.getText()).doubleValue();
            Double valorVenda = NumberFormat.getInstance().parse(textValorVenda.getText()).doubleValue();
            Double valorDesconto = NumberFormat.getInstance().parse(textDesconto.getText()).doubleValue();
            Double valorAcrescimo = NumberFormat.getInstance().parse(textAcrescimo.getText()).doubleValue();
            
            
            item.setValorCusto(valorCusto);
            item.setValorVenda(valorVenda);
            item.setDesconto(valorDesconto);
            item.setAcrescimo(valorAcrescimo);
            
        } catch (ParseException ex) {
            Logger.getLogger(ItensPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        item.setQuantidade(Integer.parseInt(textQuantidade.getText()));
        item.setMensagem(Boolean.TRUE);
        
        if(textIdFornecedor.getText().equals("")){
//            Fornecedores fornecedor = new Fornecedores();
//            
//            fornecedor.setNome(textFornecedor.getText());
//            fornecedor.setDataCadastro(Date.valueOf(textDataHoje.getText()));
//            fornecedor.setDataAlteracao(Date.valueOf(textDataHoje.getText()));
//            fornecedor.setCodEstado(18);//Código estado do Rio de Janeiro
//            fornecedor.setMensagem(false); //Não precisa informar a mensagem de sucesso ou erro.
//            
//            item.setCodFornecedor(fornecedor.consultaUltimoId());
//            
//            fornecedor.cadastraFornecedor();
            item.setCodFornecedor(1);
            
            
        }else{
            item.setCodFornecedor(Integer.parseInt(textIdFornecedor.getText()));
        }
        
        item.alteraItem();
        limpaDados();
        bloqueiaBotoes();
        preencheComboFornecedor();
        preencheTabelaItens(item.consultaItem());
        // TODO add your handling code here:
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        item = new Itens();
        
        item.setIdItens(Integer.parseInt(textIdItem.getText()));
        item.setMensagem(Boolean.TRUE);
        
        item.excluiItem();
        limpaDados();
        bloqueiaBotoes();
        preencheTabelaItens(item.consultaItem());
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void textBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscaActionPerformed

        item = new Itens();
        
        preencheTabelaItens(item.consultaItem() + " WHERE nome LIKE '%" + textBusca.getText() + "%'");
        

// TODO add your handling code here:
    }//GEN-LAST:event_textBuscaActionPerformed

    private void tabelaItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaItensMouseClicked
        
        int itemSelecionado = tabelaItens.getSelectedRow();
        
        btIncluir.setEnabled(false);
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
        
        textItem.setText(tabelaItens.getValueAt(itemSelecionado, 0).toString());
        preencheDadosItem();
        
// TODO add your handling code here:
    }//GEN-LAST:event_tabelaItensMouseClicked

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        item = new Itens();
        bloqueiaBotoes();
        limpaDados();
        preencheTabelaItens(item.consultaItem());
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarActionPerformed

    private void textQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textQuantidadeKeyTyped
        metodo = new Metodos();
        
        metodo.somenteNumeros(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_textQuantidadeKeyTyped

    private void textValorCustoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textValorCustoKeyTyped
        metodo = new Metodos();
        metodo.somenteDouble(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_textValorCustoKeyTyped

    private void textValorVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textValorVendaKeyTyped
        metodo = new Metodos();
        metodo.somenteDouble(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorVendaKeyTyped

    private void textDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDescontoKeyTyped
        metodo = new Metodos();
        metodo.somenteDouble(evt);
        
// TODO add your handling code here:
    }//GEN-LAST:event_textDescontoKeyTyped

    private void textAcrescimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAcrescimoKeyTyped
        metodo = new Metodos();
        metodo.somenteDouble(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_textAcrescimoKeyTyped

    private void comboFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFornecedorActionPerformed
        textFornecedor.setText(String.valueOf(comboFornecedor.getSelectedItem()));
        ocultaCombo();          // TODO add your handling code here:
    }//GEN-LAST:event_comboFornecedorActionPerformed

    
    public void preencheDadosItem(){
        
        try{
            String sql = "SELECT i.*, f.nome, f.idFornecedor "
                    + "FROM itens i "
                    + "INNER JOIN fornecedores f ON i.codFornecedor = f.idFornecedor "
                    + "WHERE i.nome = '" + textItem.getText() + "'";
            con = new Conexao();
            conn = con.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
            rs.next();
            
            textFornecedor.setText(rs.getString("f.nome"));
            textDesconto.setText(rs.getString("i.desconto"));
            textAcrescimo.setText(rs.getString("i.acrescimo"));
            textValorVenda.setText(rs.getString("i.valorVenda"));
            textValorCusto.setText(rs.getString("i.valorCusto"));
            textQuantidade.setText(rs.getString("i.quantidade"));
            textIdItem.setText(rs.getString("i.idItem"));
            textIdFornecedor.setText(rs.getString("f.idFornecedor"));
            
            
        }catch(IOException | SQLException ex){
            labelMensagem.setVisible(true);
            labelMensagem.setText("Não foi possível realizar a consulta. Erro: " + ex.getMessage());
        }
        
    }
    
    public void preencheComboFornecedor(){
        Fornecedores fornecedor = new Fornecedores();
        
        fornecedor.preencheComboFornecedores(comboFornecedor);
        
    }
    
    public void preencheTabelaItens(String sql){
        ArrayList dados = new ArrayList();
        String[] nomeColunas = new String[]{"ITEM","VALOR VENDA"};
//        Metodos metodo = new Metodos();
//        metodo.salvarTexto(sql);
        try{
            con = new Conexao();
            Connection conn = con.getConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            rs.first();
            
            if (rs.absolute(1)){
                do{
                    dados.add(new Object[]{rs.getString("nome"), rs.getString("valorVenda")});
                }while(rs.next());
            }else{
                labelMensagem.setVisible(true);
                labelMensagem.setText("Não contém dados na tabela. Insira um novo.");
            }
            
        ModeloTabela modelo = new ModeloTabela(dados, nomeColunas);
        tabelaItens.setModel(modelo);
        tabelaItens.getColumnModel().getColumn(0).setPreferredWidth(180); // define o tamanho da coluna.
        tabelaItens.getColumnModel().getColumn(0).setResizable(false);// Não poderá alterar o tamanho.
        tabelaItens.getColumnModel().getColumn(1).setPreferredWidth(100); // define o tamanho da coluna.
        tabelaItens.getColumnModel().getColumn(1).setResizable(false);// Não poderá alterar o tamanho.
        
        tabelaItens.getTableHeader().setReorderingAllowed(false);
        tabelaItens.setAutoResizeMode(tabelaItens.AUTO_RESIZE_OFF);
        
        tabelaItens.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
        }catch(IOException | SQLException ex){
            JOptionPane.showMessageDialog(null, "Problemas. Erro: " + ex.getMessage());
            labelMensagem.setVisible(true);
//            labelMensagem.setText("Não há registro na tabela. Inclua um novo.");
        }
        
    }
    
    
    public void preencheLabels(){
        labelItem.setText("Nome do Item:");
        labelBusca.setText("Busca: ");
        labelDesconto.setText("Desconto:");
        labelFornecedor.setText("Fornecedor:");
        labelQuantidade.setText("Quantidade:");
        labelValorCusto.setText("Valor Custo:");
        labelValorVenda.setText("Valor Venda:");
        textDesconto.setText("0.0");
        textAcrescimo.setText("0.0");
        textQuantidade.setText("0");
        textValorCusto.setText("0.0");
        textValorVenda.setText("0.0");
        labelMensagem.setVisible(false);
    }
    
    public void preencheDataHora(){
        Date dataHoje = new Date(System.currentTimeMillis());
        SimpleDateFormat formatoSql = new SimpleDateFormat("yyyy-MM-dd");
        String formatoInsereSql = formatoSql.format(dataHoje);
        textDataHoje.setText(String.valueOf(formatoInsereSql));
    }
    
    public void ocultaCombo(){
        comboFornecedor.setVisible(false);
        textIdItem.setVisible(false);
        textIdFornecedor.setVisible(false);
        textDataHoje.setVisible(false);
    }
    
    public void bloqueiaBotoes(){
        btIncluir.setEnabled(true);
        btAlterar.setEnabled(false);
        btExcluir.setEnabled(false);
    }
    
    public void limpaDados(){
        textAcrescimo.setText("");
        textBusca.setText("");
        textAcrescimo.setText("");
        textFornecedor.setText("");
        textIdFornecedor.setText("");
        textItem.setText("");
        textQuantidade.setText("");
        textValorCusto.setText("");
        textValorVenda.setText("");
        textDesconto.setText("");
        textAcrescimo.setText("");
        preencheLabels();
        textItem.requestFocus();
    }
    
    public void fechar(){
        this.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btSelectFornecedor;
    private javax.swing.JComboBox comboFornecedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAcrescimo;
    private javax.swing.JLabel labelBusca;
    private javax.swing.JLabel labelDesconto;
    private javax.swing.JLabel labelFornecedor;
    private javax.swing.JLabel labelItem;
    private javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelValorCusto;
    private javax.swing.JLabel labelValorVenda;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelItens;
    private javax.swing.JTable tabelaItens;
    private javax.swing.JTextField textAcrescimo;
    private javax.swing.JTextField textBusca;
    private javax.swing.JTextField textDataHoje;
    private javax.swing.JTextField textDesconto;
    private javax.swing.JTextField textFornecedor;
    private javax.swing.JTextField textIdFornecedor;
    private javax.swing.JTextField textIdItem;
    private javax.swing.JTextField textItem;
    private javax.swing.JTextField textQuantidade;
    private javax.swing.JTextField textValorCusto;
    private javax.swing.JTextField textValorVenda;
    // End of variables declaration//GEN-END:variables
}
