/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.cloudrestaurant.panels;

import br.com.cloudrestaurant.classes.Propriedades;
/**
 *
 * @author Debug
 */
public class PropriedadesPanel extends javax.swing.JPanel {
    Propriedades propriedades;
    /**
     * Creates new form Propriedades
     */
    public PropriedadesPanel() {
        initComponents();
    }
    
   
    
    public void fechar(){
        this.setVisible(false);
    }
    
    public void preencheLabels(){
        labelOrgao.setText("Órgão: ");
        labelTributo.setText("Valor do tributo: ");
        textTipo.setText("icms");
        //Preenche tabs
        panelIndicadores.setTitleAt(0, "ICMS   ");
        panelIndicadores.setTitleAt(1, "Desconto");
        panelIndicadores.setTitleAt(2, "Acréscimo");
        labelTitulo.setText("ICMS");
    }


    public void preencheTabs(){
//        panelIndicadores;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIndicadores = new javax.swing.JTabbedPane();
        panelIcms = new javax.swing.JPanel();
        labelOrgao = new javax.swing.JLabel();
        textOrgao = new javax.swing.JTextField();
        labelTributo = new javax.swing.JLabel();
        textTributo = new javax.swing.JTextField();
        labelNatureza = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textNatureza = new javax.swing.JTextArea();
        panelDesconto = new javax.swing.JPanel();
        labelDesconto = new javax.swing.JLabel();
        textDesconto = new javax.swing.JTextField();
        textValorDesc = new javax.swing.JTextField();
        labelTributoDesc = new javax.swing.JLabel();
        labelNaturezaDesc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textNaturezaDesc = new javax.swing.JTextArea();
        panelAcrescimo = new javax.swing.JPanel();
        labelAcrescimo = new javax.swing.JLabel();
        textAcrescimo = new javax.swing.JTextField();
        textValorAcresc = new javax.swing.JTextField();
        labelValorAcresc = new javax.swing.JLabel();
        labelNaturezaAcresc = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textNaturezaAcresc = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        labelAcrescimo1 = new javax.swing.JLabel();
        textAcrescimo1 = new javax.swing.JTextField();
        textValorAcresc1 = new javax.swing.JTextField();
        labelValorAcresc1 = new javax.swing.JLabel();
        labelNaturezaAcresc1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textNaturezaAcresc1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        labelAcrescimo2 = new javax.swing.JLabel();
        textAcrescimo2 = new javax.swing.JTextField();
        textValorAcresc2 = new javax.swing.JTextField();
        labelValorAcresc2 = new javax.swing.JLabel();
        labelNaturezaAcresc2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textNaturezaAcresc2 = new javax.swing.JTextArea();
        textTipo = new javax.swing.JTextField();
        panelBotoes = new javax.swing.JPanel();
        btCarrega = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        panelDown = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();

        panelIndicadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelIndicadoresMouseClicked(evt);
            }
        });

        labelOrgao.setText("jLabel1");

        labelTributo.setText("jLabel2");

        labelNatureza.setText("jLabel1");

        textNatureza.setColumns(20);
        textNatureza.setRows(5);
        jScrollPane1.setViewportView(textNatureza);

        javax.swing.GroupLayout panelIcmsLayout = new javax.swing.GroupLayout(panelIcms);
        panelIcms.setLayout(panelIcmsLayout);
        panelIcmsLayout.setHorizontalGroup(
            panelIcmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIcmsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIcmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelIcmsLayout.createSequentialGroup()
                        .addGroup(panelIcmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIcmsLayout.createSequentialGroup()
                                .addGroup(panelIcmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelOrgao)
                                    .addComponent(labelTributo))
                                .addGap(68, 68, 68)
                                .addGroup(panelIcmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textTributo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelNatureza))
                        .addGap(0, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelIcmsLayout.setVerticalGroup(
            panelIcmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIcmsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIcmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrgao)
                    .addComponent(textOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIcmsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTributo)
                    .addComponent(textTributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNatureza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelIndicadores.addTab("ICMS   ", panelIcms);

        labelDesconto.setText("jLabel1");

        labelTributoDesc.setText("jLabel2");

        labelNaturezaDesc.setText("jLabel1");

        textNaturezaDesc.setColumns(20);
        textNaturezaDesc.setRows(5);
        jScrollPane2.setViewportView(textNaturezaDesc);

        javax.swing.GroupLayout panelDescontoLayout = new javax.swing.GroupLayout(panelDesconto);
        panelDesconto.setLayout(panelDescontoLayout);
        panelDescontoLayout.setHorizontalGroup(
            panelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescontoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelDescontoLayout.createSequentialGroup()
                        .addGroup(panelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDescontoLayout.createSequentialGroup()
                                .addGroup(panelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDesconto)
                                    .addComponent(labelTributoDesc))
                                .addGap(68, 68, 68)
                                .addGroup(panelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textValorDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelNaturezaDesc))
                        .addGap(0, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDescontoLayout.setVerticalGroup(
            panelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescontoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesconto)
                    .addComponent(textDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDescontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTributoDesc)
                    .addComponent(textValorDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNaturezaDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelIndicadores.addTab("Desconto", panelDesconto);

        labelAcrescimo.setText("jLabel1");

        labelValorAcresc.setText("jLabel2");

        labelNaturezaAcresc.setText("jLabel1");

        textNaturezaAcresc.setColumns(20);
        textNaturezaAcresc.setRows(5);
        jScrollPane3.setViewportView(textNaturezaAcresc);

        javax.swing.GroupLayout panelAcrescimoLayout = new javax.swing.GroupLayout(panelAcrescimo);
        panelAcrescimo.setLayout(panelAcrescimoLayout);
        panelAcrescimoLayout.setHorizontalGroup(
            panelAcrescimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcrescimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAcrescimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(panelAcrescimoLayout.createSequentialGroup()
                        .addGroup(panelAcrescimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAcrescimoLayout.createSequentialGroup()
                                .addGroup(panelAcrescimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAcrescimo)
                                    .addComponent(labelValorAcresc))
                                .addGap(68, 68, 68)
                                .addGroup(panelAcrescimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textValorAcresc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelNaturezaAcresc))
                        .addGap(0, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAcrescimoLayout.setVerticalGroup(
            panelAcrescimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcrescimoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAcrescimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAcrescimo)
                    .addComponent(textAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAcrescimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorAcresc)
                    .addComponent(textValorAcresc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNaturezaAcresc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelIndicadores.addTab("Acréscimo", panelAcrescimo);

        labelAcrescimo1.setText("jLabel1");

        labelValorAcresc1.setText("jLabel2");

        labelNaturezaAcresc1.setText("jLabel1");

        textNaturezaAcresc1.setColumns(20);
        textNaturezaAcresc1.setRows(5);
        jScrollPane4.setViewportView(textNaturezaAcresc1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAcrescimo1)
                                    .addComponent(labelValorAcresc1))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAcrescimo1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textValorAcresc1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelNaturezaAcresc1))
                        .addGap(0, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAcrescimo1)
                    .addComponent(textAcrescimo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorAcresc1)
                    .addComponent(textValorAcresc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNaturezaAcresc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelIndicadores.addTab("tab4", jPanel1);

        labelAcrescimo2.setText("jLabel1");

        labelValorAcresc2.setText("jLabel2");

        labelNaturezaAcresc2.setText("jLabel1");

        textNaturezaAcresc2.setColumns(20);
        textNaturezaAcresc2.setRows(5);
        jScrollPane5.setViewportView(textNaturezaAcresc2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAcrescimo2)
                                    .addComponent(labelValorAcresc2))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAcrescimo2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textValorAcresc2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelNaturezaAcresc2))
                        .addGap(0, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAcrescimo2)
                    .addComponent(textAcrescimo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorAcresc2)
                    .addComponent(textValorAcresc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNaturezaAcresc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelIndicadores.addTab("tab5", jPanel2);

        panelBotoes.setBackground(new java.awt.Color(153, 153, 255));
        panelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btCarrega.setToolTipText("Carrega o Indicador");
        btCarrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregaActionPerformed(evt);
            }
        });

        btSalvar.setToolTipText("Salvar as informações");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btFechar.setToolTipText("Fechar");
        btFechar.setMaximumSize(new java.awt.Dimension(55, 35));
        btFechar.setMinimumSize(new java.awt.Dimension(55, 35));
        btFechar.setPreferredSize(new java.awt.Dimension(55, 35));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCarrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSalvar)))
                    .addComponent(btFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCarrega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelDown.setBackground(new java.awt.Color(153, 153, 255));

        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("jLabel1");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDownLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelTitulo))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelIndicadores, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTipo)
                            .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIndicadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelIndicadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIndicadoresMouseClicked
        if (panelIndicadores.getSelectedIndex() == 0){
            textTipo.setText("icms");
            labelTitulo.setText("ICMS");

        }
        else if (panelIndicadores.getSelectedIndex() == 1){
            textTipo.setText("desconto");
            labelTitulo.setText("DESCONTO");
        }
        else if (panelIndicadores.getSelectedIndex() == 2){
            textTipo.setText("acrescimo");
            labelTitulo.setText("ACRÉSCIMO");

        }

        /*        switch (panelIndicadores.getTitleAt(0)) {
            case 0:
            textTipo.setText("icms");
            break;
            case 1:
            textTipo.setText("desconto");
            break;
            case 2:
            textTipo.setText("acrescimo");
        }*/
    }//GEN-LAST:event_panelIndicadoresMouseClicked

    private void btCarregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregaActionPerformed
        propriedades = new Propriedades();

        propriedades.consultaIndicador();

        textOrgao.setText(propriedades.getNome());
        textTributo.setText(String.valueOf(propriedades.getValor()));

        // TODO add your handling code here:
    }//GEN-LAST:event_btCarregaActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        propriedades = new Propriedades();

        propriedades.setNome(textOrgao.getText());
        propriedades.setValor(Double.parseDouble(textTributo.getText()));

        propriedades.geraXml();

        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.fechar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCarrega;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelAcrescimo;
    private javax.swing.JLabel labelAcrescimo1;
    private javax.swing.JLabel labelAcrescimo2;
    private javax.swing.JLabel labelDesconto;
    private javax.swing.JLabel labelNatureza;
    private javax.swing.JLabel labelNaturezaAcresc;
    private javax.swing.JLabel labelNaturezaAcresc1;
    private javax.swing.JLabel labelNaturezaAcresc2;
    private javax.swing.JLabel labelNaturezaDesc;
    private javax.swing.JLabel labelOrgao;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTributo;
    private javax.swing.JLabel labelTributoDesc;
    private javax.swing.JLabel labelValorAcresc;
    private javax.swing.JLabel labelValorAcresc1;
    private javax.swing.JLabel labelValorAcresc2;
    private javax.swing.JPanel panelAcrescimo;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelDesconto;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelIcms;
    private javax.swing.JTabbedPane panelIndicadores;
    private javax.swing.JTextField textAcrescimo;
    private javax.swing.JTextField textAcrescimo1;
    private javax.swing.JTextField textAcrescimo2;
    private javax.swing.JTextField textDesconto;
    private javax.swing.JTextArea textNatureza;
    private javax.swing.JTextArea textNaturezaAcresc;
    private javax.swing.JTextArea textNaturezaAcresc1;
    private javax.swing.JTextArea textNaturezaAcresc2;
    private javax.swing.JTextArea textNaturezaDesc;
    private javax.swing.JTextField textOrgao;
    private javax.swing.JTextField textTipo;
    private javax.swing.JTextField textTributo;
    private javax.swing.JTextField textValorAcresc;
    private javax.swing.JTextField textValorAcresc1;
    private javax.swing.JTextField textValorAcresc2;
    private javax.swing.JTextField textValorDesc;
    // End of variables declaration//GEN-END:variables
}
