/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.cloudrestaurant.panels;

/**
 *
 * @author Debug
 */
public class Sobre extends javax.swing.JPanel {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagem = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelVersao = new javax.swing.JLabel();
        jLabelDireitos = new javax.swing.JLabel();
        separadorBaixo = new javax.swing.JSeparator();
        panelSistema = new javax.swing.JPanel();
        jLabelFuncao = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelExtensao = new javax.swing.JLabel();
        jLabelSite = new javax.swing.JLabel();
        jLabelTelefones = new javax.swing.JLabel();
        jLabelSGE = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(633, 257));

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/logoMapTi200x100.png"))); // NOI18N
        jLabelImage.setText("imagem");
        jLabelImage.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabelImage.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabelImage.setOpaque(true);
        jLabelImage.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout panelImagemLayout = new javax.swing.GroupLayout(panelImagem);
        panelImagem.setLayout(panelImagemLayout);
        panelImagemLayout.setHorizontalGroup(
            panelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImagemLayout.setVerticalGroup(
            panelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelAutor.setText("Autor: Michel Pereira");

        jLabelVersao.setText("Versão 1.3");

        jLabelDireitos.setText("Todos os direitos reservados.");

        panelSistema.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelFuncao.setText("Desenvolvimento de sistemas customizáveis e em nuvem (Cloud Computing).");

        jLabelEmail.setText("E-mail: pereira.michel@gmail.com ou michel@mapti.com.br");

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNome.setText("MAP TI");

        jLabelExtensao.setText("Sistema para Restaurantes customizável");

        jLabelSite.setText("Site: http://www.mapti.com.br");

        jLabelTelefones.setText("Telefones para contato: (21) 99569-1391 (Vivo) e (21) 98243-1674 (Tim)");

        jLabelSGE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSGE.setText("Cloud Restaurante");

        javax.swing.GroupLayout panelSistemaLayout = new javax.swing.GroupLayout(panelSistema);
        panelSistema.setLayout(panelSistemaLayout);
        panelSistemaLayout.setHorizontalGroup(
            panelSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelExtensao)
                    .addComponent(jLabelSGE)
                    .addComponent(jLabelFuncao)
                    .addComponent(jLabelSite)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelTelefones))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSistemaLayout.setVerticalGroup(
            panelSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome)
                .addGap(15, 15, 15)
                .addComponent(jLabelSGE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExtensao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudrestaurant/images/btSairCloud.png"))); // NOI18N
        btSair.setToolTipText("Fechar a janela");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDireitos)
                    .addComponent(jLabelVersao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelAutor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(separadorBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair)
                    .addComponent(panelSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(separadorBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabelAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVersao)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDireitos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.fechar();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    public void fechar(){
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelDireitos;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelExtensao;
    private javax.swing.JLabel jLabelFuncao;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSGE;
    private javax.swing.JLabel jLabelSite;
    private javax.swing.JLabel jLabelTelefones;
    private javax.swing.JLabel jLabelVersao;
    private javax.swing.JPanel panelImagem;
    private javax.swing.JPanel panelSistema;
    private javax.swing.JSeparator separadorBaixo;
    // End of variables declaration//GEN-END:variables
}
